name: Makefile CI

on:
  push:
    branches: [ "openwrt-21.02" ]
  pull_request:
    branches: [ "openwrt-21.02" ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v3
    
    - name: install tools
      run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'

    - name: update feeds
      run: ./scripts/feeds update -a
      
    - name: install feeds
      run: ./scripts/feeds update -a
      
#    - name: copy .config file
#      run:  |
#            cp -f defconfig/mt7986-ax6000.config .config
#            make menuconfig

    - name: get lgs2007m config
      run: wget https://raw.githubusercontent.com/lgs2007m/Actions-OpenWrt/main/hanwckf/Redmi-AX6000/.config

    - name: final make
      run: make V=s
      
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: immortalwrt-mt798x
        path: immortalwrt-mt798x/bin
